### ISSUE TITLE
Spam protection

### ISSUE THREAD

**Issue by kenany** [KenanY/nwitch#1]
## Links protection

Parse a list of spam links and timeout users who post those links.
## Repetition protection

I don't see this being easy to implement. #5 might be the best solution to this.
## TODO
- [ ] Links protection
- [ ] Spam/repetition protection
- [ ] Custom timeout messages
- [ ] Custom timeout thresholds
